feat: fix sub aar issues, gurantee successful packaging
kezong/fat-aar-android pull request #256
Opened 2020-12-23 08:30 UTC by SusionSuc

感谢作者的开源项目，为我提供了很大的帮助， 使用这个项目成功把我们相关的170多个依赖打成了一个aar， 点赞！

不过我在使用过程中发现了一些阻塞打包的问题，由于时间问题，fork了工程做了一些临时解决方案 :

- 子依赖中定义了一些不规范的 `<declare-style/>`, 和系统依赖发生冲突
> 解决方案 : 直接删除定义不规范的`<declare-style/>`

- 子依赖重复定义了`<application/>`的 attr, 导致打包失败
> 解决方案 : 删除子依赖定义的attr， 如果需要直接定义在主aar中

- 子依赖直接存在重复的so文件
> 解决方案: 可以直接删除某个子依赖的so

- fataar支持abi-filter, 这样打出来的aar会小很多(当然也可以放到接入方去做)
> 解决方案:解包子aar时删除不需要的abi 

- 最终合成的values.xml中会存在重复的`<attr/>`, 这样会导致宿主打包时失败
>解决方案: fataar打包时对values.xml进行拆分，避免同一个`<attr/>`在一个文件中

这个PR辛苦review一下，有什么问题及时沟通，希望在我们业务场景下，后续的fataar的迭代可以直接使用主分支的插件~

2020-12-23 13:03 UTC, kezong commented
内容有些多，这两天我比较忙，我会抽时间review。

2020-12-28 14:11 UTC, kezong requested changes
我review了一下，有些不明白的地方，也有一些建议，你可以补充和参考一下。

2020-12-28 14:11 UTC, kezong commented on source/src/main/java/com/kezong/fataar/PackerHelper.java
> +    private static void splitRepeatAttr(File valueXmlDir, final File file) {
这个能否举一个case，没太明白具体做什么的。

2020-12-28 14:11 UTC, kezong commented on source/src/main/groovy/com/kezong/fataar/FatAarExtension.groovy
> +    public HashMap<String, HashSet<String>> excludeDeclareStyleAttrs = new HashMap<>()
这些新加的extension，能否在example里示例一下用法。

2020-12-29 02:11 UTC, SusionSuc commented
> 我review了一下，有些不明白的地方，也有一些建议，你可以补充和参考一下。

2020-12-29 02:11 UTC, SusionSuc commented
> 我review了一下，有些不明白的地方，也有一些建议，你可以补充和参考一下。

好的，我后面找时间fix一下

2020-12-29 10:52 UTC, SusionSuc commented on source/src/main/groovy/com/kezong/fataar/VariantProcessor.groovy
> -            FatUtils.logAnytime("[embed detected][$self.type]${self.moduleVersion.id}")
日志我做了一下整理，现在直接打印到了一个单独的文件中 ： build/intermediates/fat-aar/log.txt

2020-12-30 02:18 UTC, SusionSuc commented
我发现我这个分支目前随着业务的需要，需要单独处理的点越来越多，相关的feature可能并不适合合并到主分支，我先关了这个PR，后面我看看还能不能整理一下再提PR。

2020-12-30 02:18 UTC, closed without merging

2020-12-30 04:36 UTC, kezong commented
好的，如果有什么问题和想法随时和我沟通。

2021-07-06 08:12 UTC, MoonBlueSky commented
#328 这个问题中的问题，在此PR中有相关的解决方法，是否能合并部分代码

2021-07-06 08:16 UTC, MoonBlueSky commented
#328  该问题即下方的典例
“子依赖中定义了一些不规范的 <declare-style/>, 和系统依赖发生冲突” 
希望作者大大能帮忙此PR中合一下部分必要的代码，提高库的健壮性 @kezong

2021-11-29 08:58 UTC, ruijun commented
@SusionSuc 你好，这两个扩展属性excludeDeclareStyleAttrs和excludeApplicationAttr，怎样使用呢？

2022-07-14 11:50 UTC, monkeydbobo commented on source/build.gradle
> +    implementation "org.dom4j:dom4j:2.1.3"
这个地方的dom4j的引用，可能会导致 org.xml.sax.SAXNotRecognizedException: unrecognized feature [http://xml.org/sax/features/external-general-entities]这种问题，原因是com.android.utils.PositionXmlParser#parseInternal(java.lang.String, boolean, org.xml.sax.helpers.DefaultHandler) javax.xml.parsers.SAXParserFactory#newInstance() 拿到的并不是android.tools:common的默认实现，你有遇到过这个问题吗？

2022-07-14 11:53 UTC, monkeydbobo commented on source/src/main/java/com/kezong/fataar/PackerHelper.java
> +            splitRepeatAttr(new File(pkgFile, "res/values/"), valueXml);
这个方法把同名的attr放到的不同的value.xml，但是最后打包成apk的时候，还是会有Error: Duplicate resources
[attr/xxx] .../values/values1.xml	[attr/xxx]  ..../value/values0.xml这种问题吧 @SusionSuc @kezong

2022-07-14 12:06 UTC, monkeydbobo commented on source/build.gradle
> +    implementation "org.dom4j:dom4j:2.1.3"
@kezong

2023-11-24 03:37 UTC, keisss commented on source/build.gradle
> +    implementation "org.dom4j:dom4j:2.1.3"
@monkeydbobo 同步一下，这个问题我也遇到了。解决方法是配置在依赖插件处：
```
classpath 'com.kezong:fat-aar:1.3.1', {
                exclude group: "pull-parser", module: "pull-parser"
 }
```
或者重新打包 SDK 处：
```
implementation "org.dom4j:dom4j:2.1.3" , {
                exclude group: "pull-parser", module: "pull-parser"
 }
```
可规避此问题，具体原因可以参考这里： https://github.com/dom4j/dom4j/issues/99